export function formatUiText(template, vars = {}) {
  if (!template) return ''
  return String(template).replace(/\{(\w+)\}/g, (_, key) => {
    if (vars[key] == null) return ''
    return String(vars[key])
  })
}

export const UI_FORM_DEFAULTS = {
  ui_brand_main: 'Nail',
  ui_brand_accent: '',
  ui_tagline: 'จองคิวง่าย · สะสมแต้ม',
  ui_page_title: 'Nail Thuean',
  ui_logo_url: '',
  ui_hero_image_url: '',
  ui_shop_map_url: '',
  ui_shop_map_embed_url: '',
  ui_shop_address_detail: '',
  ui_shop_location_nav_label: 'ที่อยู่ร้าน',
  ui_shop_location_page_title: 'ที่อยู่ร้าน',
  ui_shop_open_maps_btn: 'เปิดใน Google Maps',
  ui_line_chat_url: 'https://line.me',
  ui_bank_name: 'ธนาคารกสิกรไทย',
  ui_bank_account_name: 'Nail Studio',
  ui_bank_account_no: '',
  ui_promptpay_id: '',
  ui_kshop_qr_url: '',
  ui_thai_qr_label: 'สแกน Thai QR เพื่อชำระมัดจำ',
  ui_line_button_label: 'ส่งสลิปทาง LINE',
  ui_line_message_template:
    'ส่งสลิปมัดจำคิว\nBooking: {bookingId}\nวันที่: {date}\nเวลา: {start} – {end}\nยอด: {amount} บาท',
  ui_payment_page_title: 'ชำระเงินมัดจำ',
  ui_payment_slip_upload_enabled: '0',
  ui_payment_notice_off: 'กรุณาชำระมัดจำและส่งสลิปให้แอดมินยืนยัน',
  ui_payment_notice_timer:
    'กรุณาชำระภายใน {hours} ชม. นับจากเวลาจอง มิฉะนั้นคิวจะถูกยกเลิกอัตโนมัติ',
  ui_payment_hint:
    'หลังส่งสลิป แอดมินจะยืนยันการชำระเงิน และคิวจะเปลี่ยนเป็นพร้อมให้บริการ',
  ui_payment_expired: 'คิวนี้หมดเวลาชำระแล้ว ถูกยกเลิกอัตโนมัติ',
  ui_payment_not_awaiting: 'คิวนี้ไม่อยู่ในสถานะรอชำระเงินแล้ว',
  ui_qr_not_configured: 'ยังไม่ได้ตั้งค่า PromptPay ID',
  ui_qr_generate_failed: 'สร้าง QR ไม่สำเร็จ กรุณาตรวจสอบ PromptPay ID',
  ui_copy_account_hint: 'แตะเพื่อคัดลอก',
  ui_copy_success: 'คัดลอกแล้ว',
  ui_booking_success_title: 'จองแล้ว รอชำระเงิน',
  ui_booking_success_text: 'กรุณาโอนและส่งสลิปทาง LINE เพื่อรอแอดมินยืนยัน',
  ui_booking_success_btn: 'ไปหน้าชำระเงิน',
  ui_booking_fail_title: 'จองไม่สำเร็จ',
  ui_cancel_confirm_title: 'ยืนยันการยกเลิก',
  ui_cancel_confirm_text: 'ต้องการยกเลิกคิวนี้ใช่ไหม',
  ui_cancel_success_title: 'ยกเลิกสำเร็จ',
  ui_cancel_fail_title: 'ยกเลิกไม่สำเร็จ',
  ui_points_banner: 'เมื่อช่างทำเสร็จ คุณจะได้รับ <strong>+{points} แต้ม</strong>',
  ui_closed_day_error: 'ช่วงนี้ร้านปิดรับคิวทั้งวัน กรุณาเลือกวันอื่น',
  ui_no_services_today: 'ไม่มีบริการให้เลือกในวันนี้',
  ui_date_nav_hint: 'ลากเลื่อนหรือกด … เพื่อดูวันถัดไป',
  ui_no_open_days: 'ไม่มีวันเปิดรับคิวในช่วงที่เปิดจอง',
  ui_slot_taken_error: 'เวลานี้เพิ่งถูกจองแล้ว กรุณาเลือกช่วงเวลาอื่น',
  ui_extend_blocked_next_booking:
    'เวลารวมบริการของท่านยาวกว่าเวลาคิวเนื่องจากมีคิวต่อถัดไปไม่สามารถขยายเวลาได้',
  ui_extend_blocked_closing:
    'เวลารวมบริการของท่านยาวกว่าเวลาคิวเนื่องจากชนเวลาปิดร้านไม่สามารถขยายเวลาได้',
  ui_profile_title: 'บัญชีของฉัน',
  ui_profile_subtitle: 'แก้ไขข้อมูลและดูประวัติการจอง',
  ui_reviews_title: 'รีวิว',
  ui_reviews_subtitle: 'ผลงานจาก TikTok และ Instagram',
  ui_reviews_empty: 'ยังไม่มีคลิปรีวิว',
  ui_reviews_empty_hint: 'รอแอดมินเพิ่มลิงก์ TikTok หรือ Instagram',
  ui_shop_picker_title: 'เลือกร้าน',
  ui_shop_picker_subtitle: 'เลือกสาขาที่ต้องการจองคิว',
  ui_admin_add_staff_btn: 'เพิ่มช่าง',
  ui_color_primary: '#C4847A',
  ui_color_primary_dark: '#A66B62',
  ui_color_primary_light: '#F5E8E6',
}

export const UI_FIELD_GROUPS = [
  {
    title: 'แบรนด์ & รูปภาพ',
    hint: 'อัปโหลดจากมือถือได้ หรือวาง URL รูปโดยตรง · ชื่อแท็บเบราว์เซอร์ใช้ชื่อร้านจากขั้นต่อก่อน · ลิงก์ Google Maps วางลิงก์แชร์จากแอปได้เลย ระบบแสดงแผนที่ให้อัตโนมัติ',
    fields: [
      { key: 'ui_brand_main', label: 'ชื่อแบรนด์ (ส่วนหลัก)', placeholder: 'Nail' },
      { key: 'ui_brand_accent', label: 'ชื่อแบรนด์ (ส่วนเน้น)', placeholder: 'ไม่บังคับ', optional: true },
      { key: 'ui_tagline', label: 'คำโปรย', placeholder: 'จองคิวง่าย · สะสมแต้ม' },
      { key: 'ui_page_title', label: 'ชื่อแท็บเบราว์เซอร์', placeholder: 'Nail Thuean' },
      { key: 'ui_logo_url', label: 'โลโก้', placeholder: 'อัปโหลดหรือวาง URL', uploadKind: 'logo' },
      { key: 'ui_hero_image_url', label: 'ภาพปก Login', placeholder: 'อัปโหลดหรือวาง URL', uploadKind: 'hero' },
      {
        key: 'ui_shop_map_url',
        label: 'ลิงก์ Google Maps',
        placeholder: 'แชร์จากแอป Google Maps แล้ววางลิงก์',
        hint: 'เปิด Google Maps → แชร์ → คัดลอกลิงก์ วางได้เลย',
        optional: true,
      },
      {
        key: 'ui_shop_map_embed_url',
        label: 'ลิงก์ / ฝังแผนที่ (แสดงในแอป)',
        placeholder: 'จาก Google Maps → แชร์ → ฝังแผนที่ (ไม่บังคับ)',
        optional: true,
        hideInRegister: true,
        hideInAdmin: true,
      },
      {
        key: 'ui_shop_address_detail',
        label: 'รายละเอียดที่อยู่',
        placeholder: 'ชั้น 3 อาคาร X ใกล้ BTS ... (ไม่บังคับ)',
        multiline: true,
        rows: 3,
        optional: true,
      },
      {
        key: 'ui_shop_location_nav_label',
        label: 'ชื่อปุ่มแถบล่าง',
        placeholder: 'ที่อยู่ร้าน',
        hideInRegister: true,
      },
      {
        key: 'ui_shop_location_page_title',
        label: 'หัวข้อหน้าที่อยู่',
        placeholder: 'ที่อยู่ร้าน',
        hideInRegister: true,
      },
      {
        key: 'ui_shop_open_maps_btn',
        label: 'ปุ่มเปิด Maps สำรอง',
        placeholder: 'เปิดใน Google Maps',
        hideInRegister: true,
      },
    ],
  },
  {
    title: 'ชำระเงิน',
    hint: 'ลิงก์ LINE ใช้ส่งสลิปบนหน้าชำระเงิน · PromptPay หรือรูป QR KShop เลือกอย่างใดอย่างหนึ่ง (ไม่บังคับ)',
    fields: [
      {
        key: 'ui_payment_slip_upload_enabled',
        label: 'เปิดปุ่มอัปโหลดสลิปในหน้าชำระเงิน',
        type: 'toggle',
        hint: 'ปิดแล้วลูกค้ายังส่งสลิปทาง LINE ได้ตามเดิม',
        hideInRegister: true,
      },
      { key: 'ui_payment_page_title', label: 'หัวข้อหน้าชำระเงิน', hideInRegister: true },
      { key: 'ui_line_chat_url', label: 'ลิงก์ LINE (เปิดแชท — หน้าชำระเงิน)' },
      { key: 'ui_bank_name', label: 'ชื่อธนาคาร' },
      { key: 'ui_bank_account_name', label: 'ชื่อบัญชี' },
      { key: 'ui_bank_account_no', label: 'เลขบัญชี' },
      {
        key: 'ui_promptpay_id',
        label: 'PromptPay / เบอร์โทร',
        hideWhen: 'ui_kshop_qr_url',
        optional: true,
      },
      {
        key: 'ui_kshop_qr_url',
        label: 'รูป QR KShop',
        placeholder: 'อัปโหลดหรือวาง URL (ไม่บังคับ)',
        uploadKind: 'kshop_qr',
        hideWhen: 'ui_promptpay_id',
        optional: true,
      },
      { key: 'ui_thai_qr_label', label: 'ข้อความใต้ QR', hideInRegister: true },
      { key: 'ui_payment_notice_off', label: 'แจ้งเตือนชำระ (ปิดตัวจับเวลา)', multiline: true, rows: 2, hideInRegister: true },
      {
        key: 'ui_payment_notice_timer',
        label: 'แจ้งเตือนชำระ (มีตัวจับเวลา — ใช้ {hours})',
        multiline: true,
        rows: 2,
        hideInRegister: true,
      },
      { key: 'ui_payment_hint', label: 'คำแนะนำหลังส่งสลิป', multiline: true, rows: 2, hideInRegister: true },
      { key: 'ui_payment_expired', label: 'คิวหมดเวลาชำระ', hideInRegister: true },
      { key: 'ui_payment_not_awaiting', label: 'คิวไม่รอชำระแล้ว', hideInRegister: true },
      { key: 'ui_qr_not_configured', label: 'ยังไม่ตั้ง PromptPay', hideInRegister: true },
      { key: 'ui_qr_generate_failed', label: 'สร้าง QR ไม่สำเร็จ', hideInRegister: true },
      { key: 'ui_copy_account_hint', label: 'คำใบ้คัดลอกเลขบัญชี', hideInRegister: true },
      { key: 'ui_copy_success', label: 'คัดลอกสำเร็จ', hideInRegister: true },
    ],
  },
  {
    title: 'LINE',
    requiresLinePush: true,
    skipInRegister: true,
    hint: 'ข้อความปุ่มและ template ส่งสลิปทาง LINE · ใช้ {bookingId} {date} {start} {end} {amount}',
    fields: [
      { key: 'ui_line_button_label', label: 'ปุ่มส่งสลิป LINE' },
      {
        key: 'ui_line_message_template',
        label: 'ข้อความ LINE (template)',
        multiline: true,
        rows: 5,
      },
    ],
  },
  {
    title: 'ข้อความจองคิว',
    skipInRegister: true,
    fields: [
      { key: 'ui_booking_success_title', label: 'จองสำเร็จ — หัวข้อ' },
      { key: 'ui_booking_success_text', label: 'จองสำเร็จ — ข้อความ', multiline: true, rows: 2 },
      { key: 'ui_booking_success_btn', label: 'จองสำเร็จ — ปุ่ม' },
      { key: 'ui_booking_fail_title', label: 'จองไม่สำเร็จ — หัวข้อ' },
      { key: 'ui_cancel_confirm_title', label: 'ยืนยันยกเลิก — หัวข้อ' },
      { key: 'ui_cancel_confirm_text', label: 'ยืนยันยกเลิก — ข้อความ' },
      { key: 'ui_cancel_success_title', label: 'ยกเลิกสำเร็จ — หัวข้อ' },
      { key: 'ui_cancel_fail_title', label: 'ยกเลิกไม่สำเร็จ — หัวข้อ' },
      { key: 'ui_points_banner', label: 'แบนเนอร์แต้ม', multiline: true, rows: 2, placeholder: 'เมื่อช่างทำเสร็จ คุณจะได้รับ <strong>+{points} แต้ม</strong> (ใช้ {points})' },
      { key: 'ui_closed_day_error', label: 'ร้านปิดทั้งวัน' },
      { key: 'ui_no_services_today', label: 'ไม่มีบริการวันนี้' },
      { key: 'ui_date_nav_hint', label: 'คำใบ้เลื่อนดูวัน' },
      { key: 'ui_no_open_days', label: 'ไม่มีวันเปิดรับคิว' },
      { key: 'ui_slot_taken_error', label: 'เวลาถูกจองแล้ว' },
    ],
  },
  {
    title: 'หน้าอื่นๆ',
    skipInRegister: true,
    fields: [
      { key: 'ui_profile_title', label: 'หัวข้อหน้าบัญชี' },
      { key: 'ui_profile_subtitle', label: 'คำบรรยายหน้าบัญชี' },
      { key: 'ui_reviews_title', label: 'หัวข้อหน้ารีวิว' },
      { key: 'ui_reviews_subtitle', label: 'คำบรรยายหน้ารีวิว' },
      { key: 'ui_reviews_empty', label: 'ไม่มีคลิปรีวิว' },
      { key: 'ui_reviews_empty_hint', label: 'คำใบ้ไม่มีคลิป' },
      { key: 'ui_shop_picker_title', label: 'หัวข้อเลือกร้าน' },
      { key: 'ui_shop_picker_subtitle', label: 'คำบรรยายเลือกร้าน' },
    ],
  },
  {
    title: 'แอดมิน',
    skipInRegister: true,
    fields: [
      { key: 'ui_admin_add_staff_btn', label: 'ปุ่มเพิ่มช่าง (หน้าแอดมิน > ผู้ใช้)', placeholder: 'เพิ่มช่าง' },
    ],
  },
  {
    title: 'สีธีม',
    skipInRegister: true,
    hint: 'สีหลักของแอป (hex เช่น #C4847A)',
    fields: [
      { key: 'ui_color_primary', label: 'สีหลัก', type: 'color' },
      { key: 'ui_color_primary_dark', label: 'สีหลักเข้ม', type: 'color' },
      { key: 'ui_color_primary_light', label: 'สีหลักอ่อน', type: 'color' },
    ],
  },
]

export const REGISTER_UI_FIELD_GROUPS = UI_FIELD_GROUPS.filter((group) => !group.skipInRegister)
